### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by altineller** [NVIDIA/optix-toolkit#17]
Hello,

Using Ubuntu, Cuda 12.1, Nvidia Optix 7.7 I have followed the instructions and fixed alot of errors, and it does build but 2 programs fail to compile with errors:

`[100%] Linking CXX executable ../../../bin/rayCones
/usr/bin/ld: CMakeFiles/rayCones.dir/RayCones.cpp.o: in function `RayConesApp::createSBT(demandTextureApp::PerDeviceOptixState&)':
RayCones.cpp:(.text+0x367): undefined reference to `optixSbtRecordPackHeader'
/usr/bin/ld: RayCones.cpp:(.text+0x3ea): undefined reference to `optixSbtRecordPackHeader'
/usr/bin/ld: RayCones.cpp:(.text+0x56c): undefined reference to `optixSbtRecordPackHeader'
/usr/bin/ld: CMakeFiles/rayCones.dir/RayCones.cpp.o: in function `RayConesApp::buildAccel(demandTextureApp::PerDeviceOptixState&)':
RayCones.cpp:(.text+0x95b): undefined reference to `optixAccelComputeMemoryUsage'
/usr/bin/ld: RayCones.cpp:(.text+0xa53): undefined reference to `optixAccelBuild'
/usr/bin/ld: RayCones.cpp:(.text+0xb84): undefined reference to `optixAccelCompact'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/DemandLoading/RayCones/CMakeFiles/rayCones.dir/build.make:132: bin/rayCones] Error 1
make[1]: *** [CMakeFiles/Makefile2:3678: examples/DemandLoading/RayCones/CMakeFiles/rayCones.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX executable ../../../bin/testDemandLoading
[100%] Built target testDemandLoading
[100%] Linking CXX executable ../../bin/testCuOmmBaking
[100%] Built target testCuOmmBaking
[100%] Linking CXX executable ../../../bin/TestDemandGeometry
[100%] Built target TestDemandGeometry

`

any ideas or recomendations greatly appreciated.

best regards,
-C

**Comment by MarkLeone** [comment]
I believe this has been fixed, although I don't recall exactly which change fixed it.

**Comment by MarkLeone** [comment]
I thought this was fixed, but it's still an open issue.  I'll take another look.  Thanks for the heads up.

**Comment by MarkLeone** [comment]
Fixed in 65d4b2c.  Thanks for the bug report.
